version: ''

services:
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports: 
      - "9411:9411"
    restart: always  
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672    
    networks:
      - daniel-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - daniel-network

  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123    
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports: 
      - "3308:3308"
    expose:
      - 3308  
    networks:
      - daniel-network
      
  book-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123    
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports: 
      - "3310:3310"
    expose:
      - 3310  
    networks:
      - daniel-network      
      
  naming-server:
    image: danielhvitiello/naming-server:0.0.1-SNAPSHOT
    ports: 
      - "8761:8761"
    networks:
      - daniel-network
      
  api-gateway:
    image: danielhvitiello/api-gateway:0.0.1-SNAPSHOT
    ports: 
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - daniel-network

  cambio-service:
    image: danielhvitiello/cambio-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: 10-cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123      
    ports: 
      - "8000:8000"
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq      
    networks:
      - daniel-network

  book-service:
    image: danielhvitiello/book-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: 10-book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123      
    ports: 
      - "8100:8100"
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq      
    networks:
      - daniel-network
            
networks:
  daniel-network:
    driver: bridge
